server:
  port: 9191
spring:
 # zipkin:
  #  base-url: http://localhost:9411/
  h2:
    console:
      enabled: false
  application:
    name: PAYMENT-SERVICE

#logging:
 # file: C:/Users/Basant.Hota/Desktop/oms.log
